# ERROR CODES
SUCCESS_CODE = 0
GENERIC_ERROR_CODE = -1

# EXCHANGES
HUOBI = 'HUOBI'
OKEX = 'OKEX'
BINANCE = 'BINANCE'
ZB = 'ZB'
FCOIN = 'FCOIN'
AEX = 'AEX'
GATE = 'GATE'
BITFINEX = 'BITFINEX'
BITTREX = 'BITTREX'
BITMEX = 'BITMEX'
KRAKEN = 'KRAKEN'
BITSTAMP = 'BITSTAMP'
OTCBTC = 'OTCBTC'
HITBTC = 'HITBTC'
BIBOX = 'BIBOX'
LBANK = 'LBANK'
KUCOIN = 'KUCOIN'
ITBIT = 'ITBIT'
POLONIEX = 'POLONIEX'
LIQUI = 'LIQUI'
COINBIG = 'COINBIG'